[versions]
agp = "8.7.1"
kotlin = "2.1.0"
coreKtx = "1.16.0"
argsVersion ="2.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-android-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "argsVersion" }
